name: Emacs
services:
    x11-bridge:
        container_name: x11-bridge
        environment:
            - MODE=tcp
            - XPRA_HTML=yes
            - DISPLAY=:14
            - XPRA_PASSWORD=111
        network_mode: host
        image: jare/x11-bridge
    emacs:
        container_name: emacs-1
        environment:
            - DISPLAY=:14
        image: jare/emacs
        command: emacs
        depends_on:
         - x11-bridge:
        